/** Collision boxes for a block at the given coordinates. */
export function getCollisionBoxes(block: Block, x: number, y: number, z: number, out: AABB[]): void;
/** Selection/ray trace box, used for block ray tracing. */
export function getSelectionBox(block: Block, x: number, y: number, z: number): AABB | null;
export const SHAPE_EMPTY: 0;
export const SHAPE_CUBE: 1;
export const SHAPE_SLAB_BOTTOM: 2;
export const SHAPE_SLAB_TOP: 3;
export const SHAPE_STAIRS: 4;
export const SHAPE_FENCE: 5;
export const SHAPE_PANE: 6;
export const SHAPE_LIQUID: 7;
export const SHAPE_CROSS: 8;
export const SHAPE_SNOW: 9;
export const blocks: Block[];
export const AIR: number;
export const STONE: number;
export const GRASS: number;
export const DIRT: number;
export const COBBLESTONE: number;
export const PLANKS: number;
export const DIAMOND_BLOCK: number;
export const BEDROCK: number;
export const WATER: number;
export const SAND: number;
export const GRAVEL: number;
export const LOG: number;
export const LEAVES: number;
export const GLASS: number;
export const STAINED_GLASS_LIGHT_BLUE: number;
export const SNOW_LAYER: number;
export const SOUL_SAND: number;
export const SANDSTONE: number;
export const WOOL_WHITE: number;
export const GOLD_BLOCK: number;
export const IRON_BLOCK: number;
export const WOOD_DOUBLE_SLAB: number;
export const WOOD_SLAB: number;
export const STONE_SLAB_DOUBLE: number;
export const STONE_SLAB: number;
export const STONE_SLAB_TOP: number;
export const BRICK: number;
export const MOSSY_COBBLESTONE: number;
export const OBSIDIAN: number;
export const OAK_STAIRS: number;
export const FENCE: number;
export const GLOWSTONE: number;
export const STONE_BRICK: number;
export const STONE_BRICK_MOSSY: number;
export const STONE_BRICK_CRACKED: number;
export const NETHER_BRICK: number;
export const QUARTZ_BLOCK: number;
export const STONE_BRICK_STAIRS: number;
export const COBBLE_STAIRS: number;
export const ICE: number;
export const SNOW_BLOCK: number;
export const ACACIA_LOG: number;
export const BARRIER: number;
export const HARDENED_CLAY: number;
export const COAL_BLOCK: number;
export const STAINED_GLASS_PANE: number;
export const PACKED_ICE: number;
export const PLANKS_SPRUCE: number;
export const PLANKS_BIRCH: number;
export const PLANKS_JUNGLE: number;
export const PLANKS_ACACIA: number;
export const PLANKS_DARK_OAK: number;
export const WOOL_SILVER: number;
export const WOOD_DOUBLE_SLAB_SPRUCE: number;
export const WOOD_SLAB_SPRUCE: number;
export const WOOD_SLAB_TOP_SPRUCE: number;
export const STONE_BRICK_CARVED: number;
export const LOG_SPRUCE: number;
export const LEAVES_SPRUCE: number;
export const SPRUCE_FENCE: number;
export const SNOW_LAYER_2: number;
export const STAINED_CLAY_VARIANTS: number[];
import { AABB } from "../core/aabb.js";
export const FULL: AABB;
export interface Block {
	id: number;
	name: string;
	shape: number;
	solid: boolean;
	opaque: boolean;
	slipperiness: number;
	lightOpacity: number;
	lightValue: number;
	material: string;
	tint: number | null;
	tex: string | null;
	texTop: string | null;
	texBottom: string | null;
	overlaySide: string | null;
	translucent: boolean;
	glass: boolean;
	height: number;
}
