export class Input {
	constructor(canvas: HTMLCanvasElement);
	canvas: HTMLCanvasElement;
	keys: Set<string>;
	mouseButtons: Set<string>;
	binds: Record<string, string>;
	rightSources: Set<string>;
	listeners: Record<string, ((arg: unknown) => void)[]>;
	sensitivity: number;
	invertMouse: boolean;
	pointerLocked: boolean;
	expectedUnlock: boolean;
	pauseFromPointerUnlock: boolean;
	pauseFromPointerUnlockAt: number;
	suppressPauseOnUnlock: boolean;
	deltaX: number;
	deltaY: number;
	leftClicks: number;
	rightDown: boolean;
	rightPressed: boolean;
	rightReleased: boolean;
	leftDown: boolean;
	scrollDelta: number;
	hotbarRequest: number;
	ctrlDown: boolean;
	suppressLock: boolean;
	on(name: string, fn: (arg: unknown) => void): void;
	emit(name: string, arg: unknown): void;
	setBindings(bindings: Record<string, string>): void;
	setRightSource(source: string, down: boolean): void;
	releaseRight(): void;
	clear(): void;
	isDown(bind: string): boolean;
	consumeLook(): { yaw: number; pitch: number };
	consumeClicks(): number;
	consumeScroll(): number;
	consumeHotbar(): number;
	consumeRightPressed(): boolean;
	consumeRightReleased(): boolean;
	requestLock(): void;
	exitLock(): void;
}
export const DEFAULT_BINDS: Record<string, string>;
export const CONTROL_DEFS: { id: string; label: string; category: string }[];
export const SENSITIVITY_SCALE = 0.0025;
